// <auto-generated />
using System;
using Emendas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emendas.Data.Migrations
{
    [DbContext(typeof(EmendasContext))]
    [Migration("20190129030551_consertar merda fk")]
    partial class consertarmerdafk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmendasModel.Beneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("EmendasModel.Emenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmenda");

                    b.Property<int>("ParlamentarId");

                    b.Property<int?>("PlanoTrabalhoId");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ParlamentarId");

                    b.HasIndex("PlanoTrabalhoId");

                    b.ToTable("Emendas");
                });

            modelBuilder.Entity("EmendasModel.EmendaEmpenho", b =>
                {
                    b.Property<int>("EmendaId");

                    b.Property<int>("EmpenhoId");

                    b.Property<decimal>("ValorEmpenhado");

                    b.Property<decimal>("ValorPago");

                    b.HasKey("EmendaId", "EmpenhoId");

                    b.HasIndex("EmpenhoId");

                    b.ToTable("EmendaEmpenhos");
                });

            modelBuilder.Entity("EmendasModel.Empenho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoEmpenho");

                    b.HasKey("Id");

                    b.ToTable("Empenhos");
                });

            modelBuilder.Entity("EmendasModel.Parlamentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodParlamentar");

                    b.Property<string>("Name");

                    b.Property<int>("PartidoId");

                    b.Property<int>("TipoParlamentar");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Parlamentars");
                });

            modelBuilder.Entity("EmendasModel.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<string>("Name");

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("EmendasModel.PlanoTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("PlanoTrabalhos");
                });

            modelBuilder.Entity("EmendasModel.Emenda", b =>
                {
                    b.HasOne("EmendasModel.Parlamentar", "Parlamentar")
                        .WithMany("Emendas")
                        .HasForeignKey("ParlamentarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmendasModel.PlanoTrabalho", "PlanoTrabalho")
                        .WithMany("Emendas")
                        .HasForeignKey("PlanoTrabalhoId");
                });

            modelBuilder.Entity("EmendasModel.EmendaEmpenho", b =>
                {
                    b.HasOne("EmendasModel.Emenda", "Emenda")
                        .WithMany("EmendaEmpenho")
                        .HasForeignKey("EmendaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmendasModel.Empenho", "Empenho")
                        .WithMany("EmendaEmpenhos")
                        .HasForeignKey("EmpenhoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EmendasModel.Parlamentar", b =>
                {
                    b.HasOne("EmendasModel.Partido", "Partido")
                        .WithMany("Parlamentars")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
